import json
import os
import time
from pathlib import Path
from typing import Any, Callable, Mapping
from urllib import error, request


class GitHubOAuthError(RuntimeError):
    """Raised when the GitHub OAuth device flow fails or expires."""


class GitHubApiError(RuntimeError):
    """Raised when a GitHub REST API request fails."""


class GitHubRepoService:
    """Service for GitHub OAuth device flow and Git Data API pushes."""

    DEFAULT_CLIENT_ID = "Iv23lioxhi4h5AOWArq8"
    DEFAULT_REPO_NAME = "gwen-ai-generated-mvp"
    DEFAULT_DESCRIPTION = "React Native MVP generated by Gwen AI"
    DEFAULT_BRANCH = "main"

    def __init__(self, client_id: str | None = None, timeout_seconds: int = 30):
        self.client_id = client_id or os.getenv("GITHUB_CLIENT_ID") or self.DEFAULT_CLIENT_ID
        self.timeout_seconds = timeout_seconds

    def _request_json(
        self,
        method: str,
        url: str,
        *,
        payload: Mapping[str, Any] | None = None,
        headers: Mapping[str, str] | None = None,
    ) -> Any:
        final_headers = dict(headers or {})
        if payload is not None and "Content-Type" not in final_headers:
            final_headers["Content-Type"] = "application/json"

        body = None
        if payload is not None:
            body = json.dumps(payload).encode("utf-8")

        req = request.Request(url, data=body, headers=final_headers, method=method)
        try:
            with request.urlopen(req, timeout=self.timeout_seconds) as response:
                raw = response.read().decode("utf-8", errors="replace")
                if not raw:
                    return {}
                return json.loads(raw)
        except error.HTTPError as exc:
            raw = exc.read().decode("utf-8", errors="replace")
            detail = raw
            try:
                parsed = json.loads(raw)
                if isinstance(parsed, dict):
                    detail = parsed.get("message") or parsed.get("error") or raw
            except Exception:
                pass
            raise GitHubApiError(f"GitHub API request failed for {url}: {detail}") from exc

    def request_device_and_user_code(
        self,
        callback: Callable[[dict[str, Any]], None] | None = None,
    ) -> dict[str, Any]:
        """Step 1.1: Request GitHub device code and user verification details."""
        response = self._request_json(
            "POST",
            "https://github.com/login/device/code",
            payload={"client_id": self.client_id},
            headers={"Accept": "application/json"},
        )

        if not isinstance(response, dict):
            raise GitHubOAuthError("GitHub device code response was not valid JSON.")

        required_fields = ["device_code", "user_code", "verification_uri", "interval"]
        missing = [field for field in required_fields if field not in response]
        if missing:
            raise GitHubOAuthError(f"GitHub device code response missing fields: {missing}")

        payload = {
            "device_code": response["device_code"],
            "user_code": response["user_code"],
            "verification_uri": response["verification_uri"],
            "interval": int(response.get("interval", 5)),
        }

        if callback is not None:
            callback(payload)

        return payload

    def poll_for_access_token(
        self,
        device_code: str,
        interval: int = 5,
        callback: Callable[[dict[str, Any]], None] | None = None,
    ) -> str:
        """Step 1.2: Poll for access token until the user completes device authorization."""
        sleep_interval = max(1, int(interval))
        while True:
            time.sleep(sleep_interval)
            response = self._request_json(
                "POST",
                "https://github.com/login/oauth/access_token",
                payload={
                    "client_id": self.client_id,
                    "device_code": device_code,
                    "grant_type": "urn:ietf:params:oauth:grant-type:device_code",
                },
                headers={"Accept": "application/json"},
            )

            if not isinstance(response, dict):
                raise GitHubOAuthError("Unexpected OAuth token response format.")

            error = response.get("error")
            if error == "authorization_pending":
                continue
            if error == "slow_down":
                sleep_interval += 5
                continue
            if error == "expired_token":
                raise GitHubOAuthError("GitHub device code expired before authorization completed.")
            if "access_token" in response:
                token = str(response["access_token"])
                if callback is not None:
                    callback({"access_token": token, "token_type": response.get("token_type"), "scope": response.get("scope")})
                return token
            if error:
                raise GitHubOAuthError(f"GitHub OAuth device flow failed: {error}")
            raise GitHubOAuthError("GitHub OAuth device flow did not return an access token.")

    def authenticate_device_flow(
        self,
        callback: Callable[[dict[str, Any]], None] | None = None,
    ) -> dict[str, Any]:
        device_data = self.request_device_and_user_code(callback)
        access_token = self.poll_for_access_token(
            device_code=device_data["device_code"],
            interval=device_data["interval"],
            callback=callback,
        )
        return {
            "access_token": access_token,
            "device_code": device_data["device_code"],
            "user_code": device_data["user_code"],
            "verification_uri": device_data["verification_uri"],
            "interval": device_data["interval"],
        }

    def create_repository(
        self,
        access_token: str,
        repo_name: str = DEFAULT_REPO_NAME,
        description: str = DEFAULT_DESCRIPTION,
        private: bool = True,
    ) -> dict[str, Any]:
        """Phase 2: create a new private repository under the user account."""
        response = self._request_json(
            "POST",
            "https://api.github.com/user/repos",
            payload={
                "name": repo_name,
                "private": private,
                "description": description,
                "auto_init": True,
            },
            headers={
                "Authorization": f"Bearer {access_token}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
        )

        if not isinstance(response, dict):
            raise GitHubApiError("Repository creation response was not valid JSON.")

        owner = response.get("owner", {})
        repo_owner = owner.get("login") if isinstance(owner, dict) else None
        repo_name_value = response.get("name")
        default_branch = response.get("default_branch") or self.DEFAULT_BRANCH
        if not repo_owner or not repo_name_value:
            raise GitHubApiError(f"Repository creation response missing owner/repo: {response}")

        return {
            "owner": repo_owner,
            "name": repo_name_value,
            "default_branch": default_branch,
            "html_url": response.get("html_url"),
            "full_name": response.get("full_name"),
        }

    def get_latest_commit_sha(
        self,
        access_token: str,
        owner: str,
        repo: str,
        branch: str = DEFAULT_BRANCH,
    ) -> str:
        """Step 3.1: Get the SHA of the latest commit on the default branch."""
        response = self._request_json(
            "GET",
            f"https://api.github.com/repos/{owner}/{repo}/git/ref/heads/{branch}",
            headers=self._api_headers(access_token),
        )
        if not isinstance(response, dict):
            raise GitHubApiError(f"Ref lookup for {owner}/{repo} returned invalid JSON.")
        sha = response.get("object", {}).get("sha")
        if not sha:
            raise GitHubApiError(f"Could not read latest commit SHA for {owner}/{repo} on {branch}.")
        return str(sha)

    def get_base_tree_sha(
        self,
        access_token: str,
        owner: str,
        repo: str,
        latest_commit_sha: str,
    ) -> str:
        """Step 3.2: Get the base tree SHA from the latest commit."""
        response = self._request_json(
            "GET",
            f"https://api.github.com/repos/{owner}/{repo}/git/commits/{latest_commit_sha}",
            headers=self._api_headers(access_token),
        )
        if not isinstance(response, dict):
            raise GitHubApiError(f"Commit lookup for {owner}/{repo} returned invalid JSON.")
        tree_sha = response.get("tree", {}).get("sha")
        if not tree_sha:
            raise GitHubApiError(f"Could not read base tree SHA for commit {latest_commit_sha}.")
        return str(tree_sha)

    def build_tree_payload(self, base_tree_sha: str, files: Mapping[str, str]) -> dict[str, Any]:
        """Create the GitHub Git Tree payload from a file map."""
        tree_entries = []
        for path, content in files.items():
            tree_entries.append(
                {
                    "path": path,
                    "mode": "100644",
                    "type": "blob",
                    "content": content,
                }
            )
        return {"base_tree": base_tree_sha, "tree": tree_entries}

    def create_git_tree(
        self,
        access_token: str,
        owner: str,
        repo: str,
        base_tree_sha: str,
        files: Mapping[str, str],
    ) -> str:
        """Step 3.3: Create a Git tree with all generated files. """
        payload = self.build_tree_payload(base_tree_sha, files)
        response = self._request_json(
            "POST",
            f"https://api.github.com/repos/{owner}/{repo}/git/trees",
            payload=payload,
            headers=self._api_headers(access_token),
        )
        if not isinstance(response, dict):
            raise GitHubApiError(f"Tree creation for {owner}/{repo} returned invalid JSON.")
        tree_sha = response.get("sha")
        if not tree_sha:
            raise GitHubApiError(f"Could not create a new tree for {owner}/{repo}.")
        return str(tree_sha)

    def build_commit_payload(self, latest_commit_sha: str, new_tree_sha: str) -> dict[str, Any]:
        """Build the commit request payload for the GitHub Git Data API."""
        return {
            "message": "feat: initialize Gwen AI generated MVP",
            "tree": new_tree_sha,
            "parents": [latest_commit_sha],
        }

    def create_commit(
        self,
        access_token: str,
        owner: str,
        repo: str,
        latest_commit_sha: str,
        new_tree_sha: str,
    ) -> str:
        """Step 3.4: Create a new commit pointing at the new tree."""
        payload = self.build_commit_payload(latest_commit_sha, new_tree_sha)
        response = self._request_json(
            "POST",
            f"https://api.github.com/repos/{owner}/{repo}/git/commits",
            payload=payload,
            headers=self._api_headers(access_token),
        )
        if not isinstance(response, dict):
            raise GitHubApiError(f"Git commit creation for {owner}/{repo} returned invalid JSON.")
        commit_sha = response.get("sha")
        if not commit_sha:
            raise GitHubApiError(f"Could not create a new commit for {owner}/{repo}.")
        return str(commit_sha)

    def update_branch_reference(
        self,
        access_token: str,
        owner: str,
        repo: str,
        branch: str,
        new_commit_sha: str,
    ) -> dict[str, Any]:
        """Step 3.5: Update the branch reference to the new commit SHA."""
        response = self._request_json(
            "PATCH",
            f"https://api.github.com/repos/{owner}/{repo}/git/refs/heads/{branch}",
            payload={"sha": new_commit_sha, "force": False},
            headers=self._api_headers(access_token),
        )
        if not isinstance(response, dict):
            raise GitHubApiError(f"Branch update for {owner}/{repo} returned invalid JSON.")
        return response

    def push_files_to_repo(
        self,
        access_token: str,
        owner: str,
        repo: str,
        files: Mapping[str, str],
        branch: str = DEFAULT_BRANCH,
    ) -> dict[str, Any]:
        """Run the complete Git Data API sequence to push files to the repository."""
        latest_commit_sha = self.get_latest_commit_sha(access_token, owner, repo, branch)
        base_tree_sha = self.get_base_tree_sha(access_token, owner, repo, latest_commit_sha)
        new_tree_sha = self.create_git_tree(access_token, owner, repo, base_tree_sha, files)
        new_commit_sha = self.create_commit(access_token, owner, repo, latest_commit_sha, new_tree_sha)
        ref_response = self.update_branch_reference(access_token, owner, repo, branch, new_commit_sha)
        return {
            "owner": owner,
            "repo": repo,
            "branch": branch,
            "latest_commit_sha": latest_commit_sha,
            "base_tree_sha": base_tree_sha,
            "new_tree_sha": new_tree_sha,
            "new_commit_sha": new_commit_sha,
            "ref_response": ref_response,
        }

    def authenticate_and_create_repository(
        self,
        repo_name: str = DEFAULT_REPO_NAME,
        description: str = DEFAULT_DESCRIPTION,
        callback: Callable[[dict[str, Any]], None] | None = None,
    ) -> dict[str, Any]:
        auth = self.authenticate_device_flow(callback)
        repo_info = self.create_repository(auth["access_token"], repo_name=repo_name, description=description)
        return {"auth": auth, **repo_info}

    def collect_files_from_directory(self, directory_path: str | os.PathLike[str]) -> dict[str, str]:
        root = Path(directory_path).resolve()
        if not root.exists():
            raise FileNotFoundError(f"Directory does not exist: {root}")

        file_map: dict[str, str] = {}
        for file_path in sorted(root.rglob("*")):
            if not file_path.is_file():
                continue
            rel_path = file_path.relative_to(root).as_posix()
            file_map[rel_path] = file_path.read_text(encoding="utf-8")
        return file_map

    def push_generated_mvp_directory(
        self,
        directory_path: str | os.PathLike[str],
        repo_name: str = DEFAULT_REPO_NAME,
        description: str = DEFAULT_DESCRIPTION,
        callback: Callable[[dict[str, Any]], None] | None = None,
    ) -> dict[str, Any]:
        auth = self.authenticate_device_flow(callback)
        access_token = auth["access_token"]
        repo_info = self.create_repository(access_token, repo_name=repo_name, description=description)
        files = self.collect_files_from_directory(directory_path)
        push_result = self.push_files_to_repo(
            access_token,
            repo_info["owner"],
            repo_info["name"],
            files,
            branch=repo_info["default_branch"],
        )
        return {"auth": auth, "repo": repo_info, "push": push_result}

    @staticmethod
    def _api_headers(access_token: str) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {access_token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }


class GitHubDeviceAuthService(GitHubRepoService):
    """Backward-compatible alias for device OAuth-driven repository actions."""

    pass
